language: java
jdk: oraclejdk8

dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

script:
  - ./gradlew clean build
  - ./gradlew bintrayPublish